package org.hallo.ams.settings.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.name
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.login_pwd
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.major
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.institute
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.allow_ips
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    private String allowIps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.role_id
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id
     *
     * @return the value of tbl_user.id
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id
     *
     * @param id the value for tbl_user.id
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.name
     *
     * @return the value of tbl_user.name
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.name
     *
     * @param name the value for tbl_user.name
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.login_pwd
     *
     * @return the value of tbl_user.login_pwd
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.login_pwd
     *
     * @param loginPwd the value for tbl_user.login_pwd
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.major
     *
     * @return the value of tbl_user.major
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.major
     *
     * @param major the value for tbl_user.major
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.institute
     *
     * @return the value of tbl_user.institute
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.institute
     *
     * @param institute the value for tbl_user.institute
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.allow_ips
     *
     * @return the value of tbl_user.allow_ips
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public String getAllowIps() {
        return allowIps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.allow_ips
     *
     * @param allowIps the value for tbl_user.allow_ips
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public void setAllowIps(String allowIps) {
        this.allowIps = allowIps == null ? null : allowIps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.role_id
     *
     * @return the value of tbl_user.role_id
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.role_id
     *
     * @param roleId the value for tbl_user.role_id
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}