package org.hallo.ams.settings.mapper;

import org.hallo.ams.settings.domain.User;

import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated Sun Apr 03 16:50:15 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据账号密码查询账号
     * @param map 账号及密码的map
     * @return 用户
     */
    User selectUserByLoginActAndLoginPwd(Map<String,Object> map);


    /**
     * 根据ID查询用户姓名
     * @param id
     * @return 用户
     */
    String selectStuNameById(String id);

}